# Generated by Django 3.1.1 on 2020-10-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=1000)),
                ('tweetid', models.BigIntegerField()),
                ('author', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=300)),
                ('website', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('handle', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('handleid', models.BigIntegerField()),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
